
[default]
base_tile_dir = "/data/slow/web_share/cruise/tiles/"
base_data_dir = "/data/raid/cruise_support/"
remote_html_dir = "/var/www/html/cruise/"
remote_server = "tvarminne"
remote_sync = true
remote_url = "https://cruise.bror.co/"
max_tile_days = 8
updated_tiles = ["globcolour",  "ostia", "ssh"]

cruise_name = "bioreactors1"
lat1 = -55
lat2 = -10
lon1 = -75
lon2 = -5
zoom_levels = [0,1,2,3,4,5,6,7,8,9]
data_dir = "@format {this.base_data_dir}/{this.cruise_name}"
tile_dir = "@format {this.base_tile_dir}/{this.cruise_name}"
remote_tile_dir = "@format {this.remote_html_dir}/tiles/{this.cruise_name}"

[default.bathy]
    vmin=-6000
    vmax=0
    levels = 61
[default.ssh]
    vmin = -0.75
    vmax = 0.75
    levels = 20
    cmap="matplotlib:RdBu_r"
[default.ostia]
    vmin = 10
    vmax = 35
    levels = 20
    cmap="tol:rainbow_WhBr"
[default.globcolour]
    vmin = -4.6
    vmax = 4.6
    levels = 50
    cmap="matplotlib:nipy_spectral"
#
# --- Directories for data ---
#

[subsea]
cruise_name = "SubSea"
lat1 = -55
lat2 = -10
lon1 = -75
lon2 = -5
zoom_levels = [0,1,2,3,4,5,6,7,8,9,10]
[subsea.ssh]
    dynaconf_merge = true
    vmin = -0.25
    vmax =  0.25
[subsea.ostia]
    dynaconf_merge = true
    vmin = 15
    vmax = 30
    cmap="gist_rainbow_r"

[omi]
cruise_name = "OceanMargins"
lat1 = -10
lat2 =  10
lon1 = -15
lon2 =  12
zoom_levels = [0,1,2,3,4,5,6,7,8,9,10]
[omi.ssh]
    dynaconf_merge = true
    vmin = -0.25
    vmax =  0.25

[wam]
# Equatorial Atlantic, 10S-10N, Gulf of Paria to the Angolan coast.
cruise_name = "WAM"
lat1 = -10
lat2 =  10
lon1 = -62
lon2 =  15
zoom_levels = [0,1,2,3,4,5,6,7,8,9,10]
[wam.ssh]
    dynaconf_merge = true
    vmin = -0.25
    vmax =  0.25
[wam.ostia]
    dynaconf_merge = true
    vmin = 20
    vmax = 31
    cmap="gist_rainbow_r"

[ecoa]
cruise_name = "ECOA"
lat1 = 24
lat2 =  44
lon1 = -82.5
lon2 =  -60
zoom_levels = [0,1,2,3,4,5,6,7,8]
[ecoa.ssh]
    dynaconf_merge = true
    vmin = -0.25
    vmax =  0.25
